### PR TITLE
Npm integration

### PR DESCRIPTION
**Pull request by resterman**
# Summary 

So... Huge huge huge changes. 

- KongOne now **only loads** scripts per se. That's it.
- Each script has its own js file.
- The resulting userscript is now minified.
- Using **Gulp**.
  - It lints code (if something seems fishy code, the linter will tell us)
  - It generates a single userscript while having each script in a separated file.
  - We can write using `ECMAScript 6` without having to worry about compatibility (the final userscript will be in `ECMAScript 5`).
  - There's the possibility to use `CoffeScript` if needed, although it's not configured yet to do so.
  - The final userscript is uglified and minified.

### CODE REVIEW

**Comment by AlphaOverall** [comment]
Wow! Awesome work! I haven't tested any of this yet, but I've spent a lot of time on a project with a similar setup and I approve; plus it makes things a lot more organized. 
Anyways, once this gets merged, remind me to update the greasyfork webhook.

**Comment by resterman** [comment]
Thanks! :smile: 

I'll wait for Ruud, Nomuit and then, after some testing, I'll merge.

**Comment by resterman** [comment]
Alpha, could you disable the Greasyfork webhook? So we merge both branches and people don't get the broken version.

**Comment by AlphaOverall** [comment]
Alright, webhook should be disabled now.

**Comment by resterman** [comment]
Thanks! :smile: 
And could you give Ruudiluca and Nomuit write permissions?

**Comment by resterman** [comment]
That's the main reason I changed the script path from a string to a regex. You should be fine doing something like `/^\/(posts|messages|private_messages)/`. This regex matches paths that start with `/posts`, `/messages` and `/private_messages`

**Comment by Ruudiluca** [comment]
Ah, wonderful! Thank you very much, I'll get onto fixing that.

**Pull request closed without merging**
